### ISSUE TITLE
Error while installing Sylius-Standard

### ISSUE THREAD

**Issue by network-spy** [Sylius/Sylius-Standard#82]
Install Sylius-Standard by writing in command line
```#composer create-project sylius/sylius-standard -s dev```
When all packages already installed, and autoload files generated, it starts creating the "app/config/parameters.yml" file and propose to set configurations with the message: 
"Some parameters are missing. Please provide them."
All parameters, which user sets, processing well except **sylius.database.name**. It sets postfix *_dev* to the end of the value(database name) and then it causes an errors. For example if I set **sylius.database.name** value like *sylius_test*, it will show next errors:
```
[Doctrine\DBAL\Exception\ConnectionException]                                              
  An exception occured in driver: SQLSTATE[42000] [1049] Unknown database 'sylius-test_dev'  

  [Doctrine\DBAL\Driver\PDOException]                        
  SQLSTATE[42000] [1049] Unknown database 'sylius-test_dev'  
                    
  [PDOException]                                             
  SQLSTATE[42000] [1049] Unknown database 'sylius-test_dev'  

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
                                  
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.
```
The same situation will be in case if I leave default value(*sylius*) of the parameter  **sylius.database.name**. It will add postfix *_dev* to the end of the value and will try to check connection with database *sylius_dev*.

**Comment by pjedrzejewski** [comment]
This is because we use different databases for diff environments, for safety. http://docs.sylius.org/en/latest/book/environments.html

Let me know if something is still not clear! Remember to run commands with appropriate ``--env``.

**Comment by youmad** [comment]
Trying to install with `composer create-project -vvv -s dev sylius/sylius-standard dart`:

```
> post-install-cmd: Incenteev\ParameterHandler\ScriptHandler::buildParameters
sylius.database.driver (pdo_mysql): 
sylius.database.host (127.0.0.1): 
sylius.database.port (null): 
sylius.database.name (sylius): dart
sylius.database.path (null): 
sylius.database.user (root): 
sylius.database.password (null): 
sylius.mailer.transport (smtp): 
sylius.mailer.host (127.0.0.1): 
sylius.mailer.port (null): 
sylius.mailer.user (null): 
sylius.mailer.password (null): 
sylius.secret (EDITME): WowSoSyliusMuchSecret
sylius.locale (en_US): 
sylius.currency (USD): 
sylius.cache ({ type: file_system }): 
sylius.phpcr.backend ({ type: doctrinedbal, connection: default, caches: { meta: doctrine_cache.providers.phpcr_meta, nodes: doctrine_cache.providers.phpcr_nodes } }): 
sylius.phpcr.workspace (default): 
sylius.phpcr.user (admin): 
sylius.phpcr.pass (admin): 
sylius.uploader.filesystem (sylius_image): 
sylius.currency_importer.open_exchange_rates (EDITME): 
sylius.currency_importer.ecb.base_currency (EUR):
paypal.express_checkout.username (EDITME): 
paypal.express_checkout.password (EDITME): 
paypal.express_checkout.signature (EDITME): 
paypal.express_checkout.sandbox (true): 
stripe.publishable_key (EDITME): 
stripe.secret_key (EDITME): 
stripe.test_mode (true): 
be2bill.identifier (EDITME): 
be2bill.password (EDITME): 
be2bill.sandbox (true): 
sylius.oauth.amazon.clientid (EDITME): 
sylius.oauth.amazon.clientsecret (EDITME): 
sylius.oauth.facebook.clientid (EDITME): 
sylius.oauth.facebook.clientsecret (EDITME): 
sylius.oauth.google.clientid (EDITME): 
sylius.oauth.google.clientsecret (EDITME): 
sylius.inventory.backorders_enabled (true): 
sylius.inventory.tracking_enabled (true): 
sylius.inventory.holding.duration ('15 minutes'): 
sylius.promotion.item_based (false): 
sylius.order.allow_guest_order (false): 
sylius.order.pending.duration ('3 hours'): 
wkhtmltopdf.bin_path (/usr/bin/wkhtmltopdf): 
wkhtmltoimage.bin_path (/usr/bin/wkhtmltoimage):
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
Reading ./composer.json
Loading config file /home/k43e/.composer/config.json
Loading config file /home/k43e/.composer/auth.json
Loading config file ./composer.json
Failed to initialize global composer: Composer could not find the config file: /home/k43e/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section


                                                                             
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.  
                                                                             


Exception trace:
 () at /home/k43e/Development/PHP/dart/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:220
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::executeCommand() at /home/k43e/Development/PHP/dart/vendor/sensio/distribution-bundle/Sensio/Bundle/DistributionBundle/Composer/ScriptHandler.php:86
 Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:225
 Composer\EventDispatcher\EventDispatcher->executeEventPhpScript() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:179
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:94
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:350
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:172
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:130
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

**Comment by michalmarcinkowski** [comment]
Confirmed.
```bash
post-install-cmd: Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache


                                                                                        
  [Doctrine\DBAL\Exception\ConnectionException]                                         
  An exception occured in driver: SQLSTATE[HY000] [1049] Unknown database 'sylius_dev'  
```

**Comment by pjedrzejewski** [comment]
This is fixed now.

**Comment by adams-david** [comment]
I installed Sylius on my server using the instructions at https://www.rosehosting.com/blog/install-sylius-on-a-debian-8-vps/

**Comment by sagikazarmark** [comment]
@pjedrzejewski can you please point me to the fix? I am using an older version (0.14) where this issue still occurs.

**Comment by zablik** [comment]
However, If you have to use provided database name (you can't create DB with "_dev" in name) you can change this in doctrine section of
app\config\config_dev.yml
